# Generated by Django 5.0.6 on 2024-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=300)),
                ("email", models.CharField(max_length=500)),
                ("telefone", models.CharField(max_length=20, null=True)),
                ("texto", models.CharField(max_length=1000, null=True)),
                ("visto", models.BooleanField(default=False)),
            ],
        ),
    ]
